from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome(executable_path='../drivers/chromedriver')
driver.implicitly_wait(20)
driver.maximize_window()
driver.get("https://hub.knime.com/")
driver.find_element_by_class_name("accept-button").click()
driver.find_element_by_css_selector('#__layout > div > div.sticky-footer > header > nav > div.login > button').click()
driver.find_element_by_id("edit-name").send_keys("faizanbukhari")
driver.find_element_by_id("edit-pass").send_keys("123.Qwertyuiop")
driver.find_element_by_css_selector("#edit-submit").click()
driver.find_element_by_class_name("avatar-profile").click()
driver.find_element_by_css_selector("div[class='login'] li:nth-child(2)").click()
driver.find_element_by_css_selector("div[class='grid-item-9 child-container'] li:nth-child(1)").click()
driver.find_element_by_css_selector("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(3) > section:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3)").click()
driver.find_element_by_css_selector("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > main:nth-child(3) > section:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > button:nth-child(2)").click()
driver.find_element_by_xpath("//input[@placeholder='space name']").send_keys("New space")
driver.find_element_by_xpath('//*[@id="confirmationForm"]/div/input').send_keys(Keys.ENTER)
driver.close()
print("space deleted")